trigger:
  tags:
    include:
      - v*
  branches:
    include:
      - develop
      - release/*
  paths:
    exclude:
      - README.md

variables:
  group: 'pipelines'
  repository: 'focal-freedom-236620/connector'
  imageTag:
  ref: $(Build.SourceBranch)
  buildTag: $(Build.BuildId)
  branchTag: $(Build.SourceBranchName)
  releaseCandidate: 'rc'

jobs:
  - job: Platform
    dependsOn: Connector
    pool: server
    variables:
      commit: b-$(buildTag)

    steps:
      - task: InvokeRESTAPI@1
        displayName: 'trigger platform job'
        inputs:
          connectionType: 'connectedServiceName'
          serviceConnection: 'Pipelines'
          method: 'POST'
          urlSuffix: '/edgeworx/_apis/build/builds?api-version=5.0'
          body: "{\"Parameters\":\"{\\\"images.connector\\\": \\\"gcr.io/$(repository):$(commit)\\\"}\", \"Definition\":{\"id\":\"5\"}}"
          waitForCompletion: 'false'

  - job: Connector
    pool:
      vmImage: 'Ubuntu-16.04'

    steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          mavenOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: false
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          goals: 'package'

      # We need nodejs for Snyk
      - task: NodeTool@0
        inputs:
          versionSpec: '8.x'
        displayName: 'Install Node.js'

      - script: |
          npm i -g snyk
          snyk monitor --project-name=ConnectorCI
        env:
          SNYK_TOKEN: $(snykToken)
        displayName: 'Snyk monitor'

      - script: |
          echo " test"
        displayName: 'tests'

      - script: |
          if [[ $(ref) == refs/tags* ]]; then
            TAG=$(echo $(ref) | sed "s|refs/tags/v||g")
            echo "##vso[task.setvariable variable=imageTag]$TAG"
          else
            LATESTTAG=$(git tag | tail -1)
            LATESTVERS=${LATESTTAG#?}
            if [ -z "$LATESTVERS" ]; then LATESTVERS=0.0.0; fi
            echo "##vso[task.setvariable variable=imageTag]$LATESTVERS-b$(buildTag)"
          fi
          echo $(imageTag)
        displayName: 'configure tagging variables'
        name: setvarStep

      - script: |
          echo "gcr.io/${repository}:b-${buildTag}" > GCR_DOCKER_IMAGE
        displayName: 'Save Docker image name and tag to GCR_DOCKER_IMAGE into artifacts'

      - task: Docker@2
        displayName: 'build and push docker'
        inputs:
          containerRegistry: 'Edgeworx GCP'
          repository: $(repository)
          command: 'buildAndPush'
          Dockerfile: 'Dockerfile'
          tags: |
            $(imageTag)
            latest

      - script: |
          echo "mvn test"
        displayName: 'api tests'

      - script: |
          cp client/target/iofog-connector-client-jar-with-dependencies.jar packaging/usr/bin/iofog-connector.jar
          cp daemon/target/iofog-connector-daemon-jar-with-dependencies.jar packaging/usr/bin/iofog-connectord.jar
        displayName: 'copy jars for packaging'

      - task: DownloadSecureFile@1
        inputs:
          secureFile: 'package_cloud'
        displayName: 'download package cloud token file'

      - task: UseRubyVersion@0
        inputs:
          versionSpec: '>= 2.5.1'
          addToPath: true
        displayName: 'install rubygem to be used to install package_cloud cli'

      - script: |
          gem install --no-document fpm
          fpm -h
          gem install package_cloud
          package_cloud -h
          echo "config file..."
          ls $(Agent.TempDirectory)/package_cloud
        displayName: 'install package_cloud cli and fpm'

      - script: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          if [[ $(ref) == refs/tags* ]]; then
            pkg_version=$version
          else
            pkg_version=$version-b$(buildTag)
          fi
          echo $pkg_version

          cd packaging
          fpm -s dir -t deb -n iofog-connector -v $pkg_version -a all --deb-no-default-config-files --after-install debian.sh --after-remove remove.sh --before-upgrade upgrade.sh --after-upgrade debian.sh etc usr
          echo "pkg maybe created"
          package=$(ls | grep *.deb)
          echo $package
          echo "##vso[task.setvariable variable=pkg_version]$pkg_version"
        displayName: 'create deb package'

      - script: |
          cd packaging
          package=$(ls | grep *.deb)
          echo "package..."
          echo $package

          declare -a UBUNTU_VERS=("precise" "trusty" "utopic" "vivid" "wily" "xenial" "bionic") #Support ubuntu versions
          declare -a DEBIAN_VERS=("wheezy" "jessie" "stretch" "buster") #Also appplies to Raspbian, See related for loop

          for version in "${UBUNTU_VERS[@]}"
          do
              package_cloud push iofog/iofog-connector-snapshots/ubuntu/${version} $package --config=$(Agent.TempDirectory)/package_cloud
          done

          for version in "${DEBIAN_VERS[@]}"
          do
              package_cloud push iofog/iofog-connector-snapshots/debian/${version} $package --config=$(Agent.TempDirectory)/package_cloud
              package_cloud push iofog/iofog-connector-snapshots/raspbian/${version} $package --config=$(Agent.TempDirectory)/package_cloud
          done
        displayName: 'publish deb to package-cloud'

      - script: |
          cd packaging
          echo $(pkg_version)
          fpm -s dir -t rpm -n iofog-connector -v $(pkg_version) -a all --rpm-os 'linux' --after-install rpm.sh --after-remove remove.sh --before-upgrade upgrade.sh --after-upgrade rpm.sh etc usr;
          echo "pkg maybe created"
          package=$(ls | grep *.rpm)
        displayName: 'create rpm package'

      - script: |
          cd packaging
          package=$(ls | grep *.rpm)
          echo "package..."
          echo $package

          declare -a FEDORA_VERS=("22" "23" "24") #Supported Fedora Versions
          declare -a REDHAT_VERS=("6" "7") #Supported Redhat versions

          for version in ${FEDORA_VERS[@]}
          do
              package_cloud push iofog/iofog-connector-snapshots/fedora/${version} $package --config=$(Agent.TempDirectory)/package_cloud
          done

          for version in ${REDHAT_VERS[@]}
          do
              package_cloud push iofog/iofog-connector-snapshots/el/${version} $package --config=$(Agent.TempDirectory)/package_cloud
          done
        displayName: 'publish rpm to package-cloud'

      - task: CopyFiles@2
        inputs:
          SourceFolder: $(System.DefaultWorkingDirectory)
          TargetFolder: $(Build.ArtifactStagingDirectory)
          Contents: |
            GCR_DOCKER_IMAGE
            packaging/*.deb
            packaging/*.rpm
          OverWrite: true
        displayName: 'copy artifacts to staging directory'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'connector'
